name: build-wasm

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.63

      - name: Build whisper WASM
        run: ./scripts/build-wasm.sh

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: app/package-lock.json

      - name: Install deps
        run: npm ci
        working-directory: app
      - name: Check SIMD flag
        run: |
          if [ -f public/wasm/whisper-web.wasm ]; then
            wasm-opt --detect-features public/wasm/whisper-web.wasm | grep -q '+simd'
          else
            node - <<'NODE'
            const fs = require('fs');
            const m = fs.readFileSync('public/wasm/whisper-web.js', 'utf8')
              .match(/data:application\/wasm;base64,([A-Za-z0-9+/=]+)/);
            if (!m) process.exit(42);
            fs.writeFileSync('/tmp/whisper.wasm', Buffer.from(m[1], 'base64'));
            NODE
            wasm-opt --detect-features /tmp/whisper.wasm | grep -q '+simd'
          fi
      - name: Post-build checks
        run: |
          test -f public/wasm/whisper-web.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: public/wasm
