name: build-wasm

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./app/package-lock.json
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.60
      - name: Install Binaryen
        run: sudo apt-get update -qq && sudo apt-get install -y binaryen
      - name: Build wasm
        run: ./scripts/build-wasm.sh
      - name: Check SIMD flag
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const m = fs.readFileSync('public/wasm/whisper.js', 'utf8')
            .match(/data:application\/wasm;base64,([A-Za-z0-9+/=]+)/);
          if (!m) process.exit(42);
          fs.writeFileSync('/tmp/whisper.wasm', Buffer.from(m[1], 'base64'));
          NODE
          wasm-opt --detect-features /tmp/whisper.wasm | grep -q '+simd'
      - name: Post-build checks
        run: |
          test -f public/wasm/whisper.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wasm
          path: public/wasm
